경제:
  alpha: 0.26
  gamma: 4
  batch_size: 32
사회?문화:
  alpha: 0.69
  gamma: 3.5
  batch_size: 32
세계사:
  alpha: 0.39
  gamma: 3.5
  batch_size: 256
윤리와 사상:
  alpha: 0.63
  gamma: 0.5
  batch_size: 64
세계지리:
  alpha: 0.17
  gamma: 5.0
  batch_size: 64
생활과 윤리:
  alpha: 0.54
  gamma: 3.5
  batch_size: 256
동아시아사:
  alpha: 0.82
  gamma: 1.5
  batch_size: 128
한국지리:
  alpha: 0.71
  gamma: 4
  batch_size: 256
물리학Ⅱ:
  alpha: 0.24
  gamma: 4
  batch_size: 512
화학Ⅰ:
  alpha: 0.46
  gamma: 4
  batch_size: 32
수학Ⅰ,수학Ⅱ:
  alpha: 0.22
  gamma: 4.5
  batch_size: 1024
독서,문학:
  alpha: 0.47
  gamma: 2
  batch_size: 128
생명과학Ⅱ:
  alpha: 0.72
  gamma: 2.5
  batch_size: 32
지구과학Ⅰ:
  alpha: 0.54
  gamma: 1.5
  batch_size: 128
지구과학Ⅱ:
  alpha: 0.24
  gamma: 5.0
  batch_size: 128
통합과학:
  alpha: 0.36
  gamma: 3
  batch_size: 128
통합사회:
  alpha: 0.27
  gamma: 1.5
  batch_size: 64
생명과학Ⅰ:
  alpha: 0.55
  gamma: 1
  batch_size: 128
한국사:
  alpha: 0.34
  gamma: 4
  batch_size: 256
독해:
  alpha: 0.72
  gamma: 0.5
  batch_size: 1024
화학Ⅱ:
  alpha: 0.31
  gamma: 3.5
  batch_size: 32
정치와 법:
  alpha: 0.36
  gamma: 2.5
  batch_size: 128
물리학Ⅰ:
  alpha: 0.35
  gamma: 3
  batch_size: 128
